personal_assistant/chat/urls.py
"""
URL Configuration for chat app.
"""

from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_view, name='chat'),
]

personal_assistant/diary/urls.py
from django.urls import path
from . import views

app_name = 'calendar'

urlpatterns = [
    path('', views.calendar_view, name='calendar_view'),
    path('add/', views.add_event, name='add_event'),
    path('delete/<int:pk>/', views.delete_event, name='delete_event'),
]

personal_assistant/personal_assistant/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from news.views import base_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_view, name='base'),
    path('contacts/', include('contacts.urls')),
    path('files/', include('files.urls')),
    # path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
    path('chat/', include('chat.urls')),
    path('calendar/', include('diary.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_assistant/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", views.profile, name="profile"),
]

personal_assistant/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Personal Assistant</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
     {% load static %}

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">

    <nav>
        <ul style="display: flex; justify-content: space-between; width: 100%; margin-bottom:36px;">
            <li style="padding-top:0px; padding-bottom:0px">
                <a href="/" style="text-decoration: none; font-size: 24px;">Personal Assistant</a>
            </li>

            {% if user.is_authenticated %}

            <li style="padding-top:0px; padding-bottom:0px">
                <a href="/contacts" style="text-decoration: none; font-size: 16px;">Contacts</a>
            </li>
            <li style="padding-top:0px; padding-bottom:0px">
                <a class="" href="/notes" style="text-decoration: none; font-size: 16px;">Notes</a>

            </li>

            <li style="padding-top:0px; padding-bottom:0px">
                <a class="" href="/files" style="text-decoration: none; font-size: 16px;">Files</a>

            </li>

             <li style="padding-top:0px; padding-bottom:0px">
                <a class="" href="" style="text-decoration: none; font-size: 16px;">Chat</a>

            </li>

             <li style="padding-top:0px; padding-bottom:0px">
                <a class="" href="{% url 'calendar:calendar_view' %}" style="text-decoration: none; font-size: 16px;">Diary</a>

            </li>

            {% endif %}

             <li style="padding-top:0px; padding-bottom:0px">
                <a class="" href="/chat" style="text-decoration: none; font-size: 16px;">Ai chat</a>

            </li>

            <li style="padding-top:0px; padding-bottom:0px">
                <ul>
                    {% if not user.is_authenticated %}
                    <li style="padding-top:0px; padding-bottom:0px"><a href="{% url 'users:signup' %}" style="text-decoration: none; font-size: 16px;">Sign Up</a></li>
                    <li style="padding-top:0px; padding-bottom:0px"><a href="{% url 'users:login' %}" style="text-decoration: none; font-size: 16px;">Login</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li style="padding-top:0px; padding-bottom:0px"><a href="{% url 'users:logout' %}" style="text-decoration: none; font-size: 16px;">Log Out</a></li>
                    <li style="padding-top:0px; padding-bottom:0px"><a href="{% url 'users:profile' %}" style="text-decoration: none; font-size: 16px;">Profile</a></li>
                    {% endif %}
                </ul>
            </li>

        </ul>

    </nav>

    {% block content %} {% endblock %}

{% include "news/news.html" %}

</main>

</body>
</html>